# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # No 'windows-latest', no trouble :)
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        # node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [10.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check for missing change logs
        run: node common/scripts/install-run-rush.js change -v
      - name: Rush install
        run: node common/scripts/install-run-rush.js install
      - name: Rush build
        run: node common/scripts/install-run-rush.js rebuild --verbose
      - name: Rush test
        run: node common/scripts/install-run-rush.js test
